### Signup
POST http://localhost:3000/api/auth/signup
Content-type : application/json

{
    "email" : "fabou291@gmail.com",
    "password" : "testTest1234."
}

### Login
POST http://localhost:3000/api/auth/login
Content-type : application/json

{
    "email" : "fabou291@gmail.com",
    "password" : "testTest1234"
}

### GET all sauces
GET http://localhost:3000/api/sauces/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwM2QwOTFmM2EwYTM1MzhmYTlmODUiLCJpYXQiOjE2MjQyNjgyMTAsImV4cCI6MTYyNDI2ODIxMX0.jj3-eZnIJYpq_M9nIojxpyWDyGVHo1IBcqjUDXceD1c


### GET one sauce
GET http://localhost:3000/api/sauces/60cc80508e23851fa4666066

### Create a sauce
POST http://localhost:3000/api/sauces
Content-type : application/json

{
  "sauce" : {
    "name": "string",
    "manufacturer": "string",
    "description": "string",
    "heat": 1,
    "imageUrl": "string",
    "mainPepper": "string",
    "userId": "string"    
  }
}

### Modify a sauce
PUT http://localhost:3000/api/sauces/60cc80508e23851fa4666066
Content-type : application/json

{
  "name": "strdddazedddding",
  "manufacturer" : "tzruc"
}

### Delete a sauce
DELETE http://localhost:3000/api/sauces/60d0a9584ab08643dc6e27ca 

### Handle likes sauces
POST http://localhost:3000/api/sauces/60cc80508e23851fa4666066/like
Content-type : application/json

{
    "userId" : "60d03d091f3a0a3538fa9f85",
    "like" : 1
}


### Test auth
GET http://localhost:3000/api/auth/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwM2QwOTFmM2EwYTM1MzhmYTlmODUiLCJpYXQiOjE2MjQyNjgyMTAsImV4cCI6MTYyNDI2ODIxMX0.jj3-eZnIJYpq_M9nIojxpyWDyGVHo1IBcqjUDXceD1c

### An unknow route
GET http://localhost:3000/unknow_route