### Signup
POST http://localhost:3000/api/auth/signup
Content-type : application/json

{
    "email" : "unautremail@gmail.com",
    "password" : "testTest1234."
}

### Login
POST http://localhost:3000/api/auth/login
Content-type : application/json

{
    "email" : "fabou291@gmail.com",
    "password" : "testTest1234."
}

### GET all sauces
GET http://localhost:3000/api/sauces/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0


### GET one sauce
GET http://localhost:3000/api/sauces/60db3cc1892a793e14d7a0ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0


### Create a sauce
POST http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0
Content-type : application/json

{
  "sauce" : {
    "name": "$gte",
    "manufacturer": "string",
    "description": "string",
    "heat": 1,
    "imageUrl": "string",
    "mainPepper": "string",
    "userId": "string"  
  }
}

### Modify a sauce
PUT http://localhost:3000/api/sauces/60cc80508e23851fa4666066
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0
Content-type : application/json

{
  "name": "strdddazedddding",
  "manufacturer" : "tzruc"
}

### Delete a sauce
DELETE http://localhost:3000/api/sauces/60d0a9584ab08643dc6e27ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0


### Handle likes sauces
POST http://localhost:3000/api/sauces/60cc80508e23851fa4666066/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRiNDViNjNkYWQwNDFiYTRiZjJjOWEiLCJpYXQiOjE2MjUwNTkzMDEsImV4cCI6MTYyNTA2MjkwMX0.Mfm39yM4ZCGjfP9WE-6JdBtNZ2W4GwInvscoeZzRiZ0
Content-type : application/json

{
    "userId" : "60d03d091f3a0a3538fa9f85",
    "like" : 1
}
